### PR TITLE
Task 9

### PR DESCRIPTION
**Pull request by vvkotov**
- [x] 3 - A working and correct express application should be in the bff-service folder. Reviewer can start this application locally with any valid configuration in the .env file and this application should works as described in the task 9.1
- [x] 5 - The bff-service should be deployed with Elastic Beanstalk. The bff-service call should be redirected to the appropriate service : product-service or CART. The response from the bff-service should be the same as if product-service or CART services were called directly.

- [x] +1 - Add a cache at the bff-service level for a request to the getProductsList function of the product-service. The cache should expire in 2 minutes.

MR in FE repo:
https://github.com/vvkotov/nodejs-aws-fe/pull/6
FE app:
https://d2041hlczfs5g6.cloudfront.net/
I would suggest to use [this file](https://docs.google.com/spreadsheets/d/1686R7uSSbOlSR91Q20tzy41rJ1fdtS96zVSPSeScDaw/edit?usp=sharing) for upload testing as CSV should be with comma separator. Also filename should be one word, without any special characters

**UPD:**
BFF service:
http://vvkotov-bff-api-dev.eu-west-1.elasticbeanstalk.com/
CART service:
http://vvkotov-cart-api-dev.eu-west-1.elasticbeanstalk.com/
API gateway proxy for BFF:
https://bybi9urpd3.execute-api.eu-west-1.amazonaws.com/dev

### CODE REVIEW

**Comment by EugeneCh** [comment]
Where's link to BFF service?

**Comment by kotmatpockuh** [comment]
@EugeneCh link is not required according to task description. Moreover, El.Beanstalk can be a money-wasting thing.... So if task #8 was working -> see no reason to blame anyone here.

6/7

**Comment by EugeneCh** [comment]
@kotmatpockuh from task 9 description
Provide your reviewers with the following information:

    link to the repo
    product-service service API endpoint URL
    example of the create product API call with all needed information: URL, payload, headers, etc.
    CART service API endpoint URL
    bff-service service URL
    example how to call product-service and CART services via bff-service service URL


And yeah, ELB is money-wasting, but in two days we can stop all the instances and 750 hours for a month is more than enough for that

**Comment by vvkotov** [comment]
Hi guys,
sorry for bad description, I've updated it

**Pull request merged**
