### PR TITLE
create product service

### PR DESCRIPTION
**Pull request by vvkotov**
**Service is done, FE is working.**
Product-service API - https://017zzup6h6.execute-api.eu-west-1.amazonaws.com/dev
FE Pull request - https://github.com/vvkotov/nodejs-aws-fe/pull/2

**Additional Scope:**

- ES6 modules are used for product-service implementation
- Webpack is configured for product-service
- Lambda handlers (getProductsList, getProductsById) code is written not in 1 single module (file) and separated in codebase.
- SWAGGER documentation is created for product-service
- Main error scenarious are handled by API ("Product not found" error, try catch blocks are used in lambda handlers) (Partially)

### CODE REVIEW

**Comment by Savsan** [comment]
Hi! Where is a link to swagger UI?

**Comment by vvkotov** [comment]
Hi, I just added swagger YAML file. If necessary, I could try to add Swagger UI by EOD.

**Comment by Savsan** [comment]
Anyway, I need to see swagger documentation working. The file by itself unnecessary. U could use SwaggerHub to apply the file and provide the link.

**Comment by vvkotov** [comment]
then just skip this point

**Comment by maksym-lebedynets** [comment]
Hello. I don't see try...catch in Lambdas. Are you sure about this point?

**Comment by maksym-lebedynets** [comment]
> Anyway, I need to see swagger documentation working. The file by itself unnecessary. U could use SwaggerHub to apply the file and provide the link.

You can just put it to https://editor.swagger.io/ to check. A deployed swagger file is not required for this task.

**Comment by vvkotov** [comment]
@maksym-lebedynets is it the only way to handle errors?
I [handled case](https://github.com/vvkotov/rss-app-be/pull/1/files#diff-fbb343388a1849e794d19b9ceaf83dfaa947bf0b3dcfded2d7b3f6c4c8cedb6fR10), when item is not found by id and thought it would be enough.

**Comment by maksym-lebedynets** [comment]
> @maksym-lebedynets is it the only way to handle errors?
> I [handled case](https://github.com/vvkotov/rss-app-be/pull/1/files#diff-fbb343388a1849e794d19b9ceaf83dfaa947bf0b3dcfded2d7b3f6c4c8cedb6fR10), when item is not found by id and thought it would be enough.

You handle the error by sending status, but I meant error which may occur in your JS code

**Pull request merged**
